const abilities = [
  // ⚪ TIER I
  { name: "Flinch Unavailable", tier: 1, desc: "Can no longer inflict [Flinch]." },
  { name: "STR +1", tier: 1, desc: "STR increases by 1." },
  { name: "INT +1", tier: 1, desc: "INT increases by 1." },
  { name: "VIT +1", tier: 1, desc: "VIT increases by 1." },
  { name: "AGI +1", tier: 1, desc: "AGI increases by 1." },
  { name: "DEX +1", tier: 1, desc: "DEX increases by 1." },
  { name: "MaxHP +200", tier: 1, desc: "MaxHP increases by 200." },
  { name: "MaxMP +10", tier: 1, desc: "MaxMP increases by 10." },
  { name: "ATK +5", tier: 1, desc: "ATK increases by 5." },
  { name: "MATK +5", tier: 1, desc: "MATK increases by 5." },
  { name: "DEF +10", tier: 1, desc: "DEF increases by 10." },
  { name: "MDEF +10", tier: 1, desc: "MDEF increases by 10." },
  { name: "Accuracy +3", tier: 1, desc: "Accuracy increases by 3." },
  { name: "Dodge +3", tier: 1, desc: "Dodge increases by 3." },
  { name: "ASPD +50", tier: 1, desc: "ASPD increases by 50." },
  { name: "CSPD +50", tier: 1, desc: "CSPD increases by 50." },
  { name: "Natural HP Regen +15", tier: 1, desc: "Natural HP Regen increases by 15." },
  { name: "Natural MP Regen +5", tier: 1, desc: "Natural MP Regen increases by 5." },
  { name: "Critical Rate +1", tier: 1, desc: "Critical Rate increases by 1." },
  { name: "Critical Damage +1", tier: 1, desc: "Critical Damage increases by 1." },
  { name: "Exp Gain +3%", tier: 1, desc: "EXP gained from monsters increases by 3%." },
  { name: "Pet EXP Gain +6%", tier: 1, desc: "EXP gained by pets increases by 6%." },
  { name: "Battlecast Lv1", tier: 1, desc: "Dealing damage to a target increases CSPD by 20 for 6 seconds. Max 20 stacks." },
  { name: "Blood Regen Lv1", tier: 1, desc: "Dealing damage to a target restores 200 HP. HP restored increases based on STR. Activates once every 3 seconds." },
  { name: "Blood Spell Lv1", tier: 1, desc: "Dealing damage to a target restores 200 HP. HP restored increases based on INT. Activates every 3 seconds." },
  { name: "Bunker Edge Lv1", tier: 1, desc: "Dealing damage to a target increases Physical Pierce by 1% for 5 seconds. Activation Power 20. Max 10 stacks." },
  { name: "Bunker Magica Lv1", tier: 1, desc: "Dealing damage to a target increases Magic Pierce by 1% for 5 seconds. Activation Power 20. Max 10 stacks." },
  { name: "Counter Evasion Mana Lv1", tier: 1, desc: "Restores 20 MP when the target performs an Evasion (excluding events). MP restored increases based on INT. Activates once every 6 seconds." },
  { name: "Counter Evasion Power Lv1", tier: 1, desc: "When the target performs an Evasion (Excluding Events), Attack increases by 100 for 10 seconds. Higher DEX leads to a greater increase. Activates once every 20 seconds." },
  { name: "Counter Rage Lv1", tier: 1, desc: "When taking damage from a target, Aggro increases by 10% for 12 seconds." },
  { name: "Counter Speed Lv1", tier: 1, desc: "When taking damage from a target, ASPD, CSPD, and Action Speed increase by 2% for 3 seconds." },
  { name: "Critical Lv1", tier: 1, desc: "Dealing damage to a target increases Critical Rate by 1 for 3 seconds. Effect duration increases based on CRT. Max 10 stacks." },
  { name: "Critical Rebound Lv1", tier: 1, desc: "If your attack is MISS, Critical Rate increases by 4 for 60 seconds. Max 5 stacks." },
  { name: "Cursed Weapon Lv1", tier: 1, desc: "Dealing damage to a target reduces Max HP by 1% for 3 seconds, but increases ATK and MATK by 1. Max 99 stacks." },
  { name: "Dash Defence Lv1", tier: 1, desc: "When using Evasion, for 3 seconds, Physical and Magical Resistance increase by 2%. Max 3 stacks." },
  { name: "Dash Power Lv1", tier: 1, desc: "When using Evasion, for 3 seconds, ATK increases by 10 and ASPD increases by 100. Max 3 stacks." },
  { name: "Engineer Lv1", tier: 1, desc: "Dealing damage to a target increases ATK and MATK by 10, and also CSPD by 10 for 20 seconds. Higher TEC leads to a greater increase. Activates once every 10 seconds." },
  { name: "Fighting Magica Lv1", tier: 1, desc: "Dealing damage to a target increases MATK by 1 for 4 seconds. Max 300 stacks." },
  { name: "Fighting Power Lv1", tier: 1, desc: "Dealing damage to a target increases ATK by 1 for 2 seconds. Max 300 stacks." },
  { name: "Foreseen Evasion Lv1", tier: 1, desc: "When the target performs an Evasion (excluding events), Anticipate increases by 5% for 12 seconds." },
  { name: "Gearshift Lv1", tier: 1, desc: "Dealing damage to a target increases ASPD by 20 for 3 seconds. Max 20 stacks." },
  { name: "Graze Mana Lv1", tier: 1, desc: "Restores 10 MP if your attack is a Graze. Activation Power 10." },
  { name: "Graze Mana Boost Lv1", tier: 1, desc: "If your attack is a Graze, for 15 seconds, MaxMP decreases by 300, but Short and Long Range Damage increases by 1%, and Accuracy increases by 60. Max 3 stacks." },
  { name: "Graze Precision Lv1", tier: 1, desc: "If your attack is a Graze, Accuracy increases by 20 for 30 seconds. Max 5 stacks." },
  { name: "Guarded Advantage Lv1", tier: 1, desc: "When the target performs a Guard (excluding events), Guard Break increases by 5% for 12 seconds." },
  { name: "Guarded Magica Lv1", tier: 1, desc: "When the target performs a Guard (excluding events), MATK increases by 50 for 10 seconds. Higher DEX leads to a greater increase. Activates once every 20 seconds." },
  { name: "Guarded Recovery Lv1", tier: 1, desc: "Restores 1000 HP when the target performs a Guard (excluding events). HP restored increases based on STR. Activates once every 6 seconds." },
  { name: "Health Barrier Lv1", tier: 1, desc: "Dealing damage to a target increases Physical Barrier and Magic Barrier by 2 for 6 seconds. Higher MTL leads to a greater increase. Max 100 stacks." },
  { name: "Life Purge Lv1", tier: 1, desc: "When taking damage from a target, for 20 seconds, MaxHP decreases by 1%, but ASPD increases by 50. Max 5 stacks." },
  { name: "Lucky Experience Lv1", tier: 1, desc: "Dealing damage to a target increases EXP Gain by 1% for 77 seconds. Max number of stacks increases based on LUK. Max 10 stacks." },
  { name: "Magica Rebound Lv1", tier: 1, desc: "If your attack is a MISS, MATK increases by 10 for 30 seconds. Max 10 stacks." },
  { name: "Mana Combat Lv1", tier: 1, desc: "Restores 1 MP when taking damage from a target, MP restored increases based on VIT." },
  { name: "Mana Rebound Lv1", tier: 1, desc: "Restores 100 MP if your attack is a MISS. Activation Power 10." },
  { name: "Mega Power Rebound Lv1", tier: 1, desc: "If your attack is a MISS, for 90 seconds, ATK increases by 100, Critical Rate increases by 50, and Accuracy decreases by 9999." },
  { name: "Nimble Lv1", tier: 1, desc: "Dealing damage to a target increases Dodge by 1 for 6 seconds. Max 30 stacks." },
  { name: "Power Rebound Lv1", tier: 1, desc: "If your attack is a MISS, ATK increases by 10 for 30 seconds. Max 10 stacks." },
  { name: "Precision Lv1", tier: 1, desc: "Dealing damage to a target increases Accuracy by 1 for 6 seconds. Max 30 stacks." },
  { name: "Spirit Blow Lv1", tier: 1, desc: "Dealing damage to a target restores 2 MP. MP restored increases based on AGI. Activates once every 6 seconds." },
  { name: "Spirit Shot Lv1", tier: 1, desc: "Dealing damage to a target restores 2 MP. MP restored increases based on DEX. Activates once every 6 seconds." },
  { name: "Vengeful Life Lv1", tier: 1, desc: "When taking damage from a target, MaxHP increases by 50 for 180 seconds. Max 120 stacks." },
  { name: "Vengeful Magica Lv1", tier: 1, desc: "When taking damage from a target, MATK increases by 10 for 30 seconds. Max 90 stacks." },
  { name: "Vengeful Mana Lv1", tier: 1, desc: "When taking damage from a target, Max MP increases by 5 for 180 seconds. Max 30 stacks." },
  { name: "Vengeful Power Lv1", tier: 1, desc: "When taking damage from a target, ATK increases by 10 for 30 seconds. Max 90 stacks." },
  { name: "Vengeful Samurai Lv1", tier: 1, desc: "When taking damage from a target, Unsheathe Power increases by 100 for 9 seconds. Max 1 stack." },

  // 🟢 TIER II
  { name: "Stun Unavailable", tier: 2, desc: "Can no longer inflict [Stun]." },
  { name: "STR +2", tier: 2, desc: "STR increases by 2." },
  { name: "INT +2", tier: 2, desc: "INT increases by 2." },
  { name: "VIT +2", tier: 2, desc: "VIT increases by 2." },
  { name: "AGI +2", tier: 2, desc: "AGI increases by 2." },
  { name: "DEX +2", tier: 2, desc: "DEX increases by 2." },
  { name: "MaxHP +400", tier: 2, desc: "MaxHP increases by 400." },
  { name: "MaxMP +20", tier: 2, desc: "MaxMP increases by 20." },
  { name: "ATK +10", tier: 2, desc: "ATK increases by 10." },
  { name: "MATK +10", tier: 2, desc: "MATK increases by 10." },
  { name: "DEF +20", tier: 2, desc: "DEF increases by 20." },
  { name: "MDEF +20", tier: 2, desc: "MDEF increases by 20." },
  { name: "Accuracy +6", tier: 2, desc: "Accuracy increases by 6." },
  { name: "Dodge +6", tier: 2, desc: "Dodge increases by 6." },
  { name: "ASPD +100", tier: 2, desc: "ASPD increases by 100." },
  { name: "CSPD +100", tier: 2, desc: "CSPD increases by 100." },
  { name: "Natural HP Regen +30", tier: 2, desc: "Natural HP Regen increases by 30." },
  { name: "Natural MP Regen +10", tier: 2, desc: "Natural MP Regen increases by 10." },
  { name: "Critical Rate +2", tier: 2, desc: "Critical Rate increases by 2." },
  { name: "Critical Damage +2", tier: 2, desc: "Critical Damage increases by 2." },
  { name: "Exp Gain +6%", tier: 2, desc: "EXP gained from monsters increases by 6%." },
  { name: "Pet EXP Gain +12%", tier: 2, desc: "EXP gained by pets increases by 12%." },
  { name: "Battlecast Lv2", tier: 2, desc: "Dealing damage to a target increases CSPD by 40 for 6 seconds. Max 20 stacks." },
  { name: "Blood Regen Lv2", tier: 2, desc: "Dealing damage to a target restores 400 HP. HP restored increases based on STR. Activates once every 3 seconds." },
  { name: "Blood Spell Lv2", tier: 2, desc: "Dealing damage to a target restores 400 HP. HP restored increases based on INT. Activates once every 3 seconds." },
  { name: "Bunker Edge Lv2", tier: 2, desc: "Dealing damage to a target increases Physical Pierce by 1% for 5 seconds. Activation Power 40. Max 10 stacks." },
  { name: "Bunker Magica Lv2", tier: 2, desc: "Dealing damage to a target increases Magic Pierce by 1% for 5 seconds. Activation power 40. Max 10 stacks." },
  { name: "Counter Evasion Mana Lv2", tier: 2, desc: "Restores 40 MP when the target performs an Evasion (excluding events). MP restored increases based on INT. Activates once every 6 seconds." },
  { name: "Counter Evasion Power Lv2", tier: 2, desc: "When the target performs an Evasion (Excluding Events), Attack increases by 100 for 15 seconds. Higher DEX leads to a greater increase. Activates once every 20 seconds." },
  { name: "Counter Rage Lv2", tier: 2, desc: "When taking damage from a target, Aggro increases by 20% for 12 seconds." },
  { name: "Counter Speed Lv2", tier: 2, desc: "When taking damage from a target, ASPD, CSPD, and Action Speed increase by 4% for 3 seconds." },
  { name: "Critical Lv2", tier: 2, desc: "Dealing damage to a target increases Critical Rate by 1 for 3 seconds. Effect duration increases based on CRT. Max 20 stacks." },
  { name: "Critical Rebound Lv2", tier: 2, desc: "If your attack is MISS, Critical Rate increases by 8 for 60 seconds. Max 5 stacks." },
  { name: "Cursed Weapon Lv2", tier: 2, desc: "Dealing damage to a target reduces Max HP by 1% for 3 seconds, but increases ATK and MATK by 2. Max 99 stacks." },
  { name: "Dash Defence Lv2", tier: 2, desc: "When using Evasion, for 3 seconds, Physical and Magic Resistance increase by 4%. Max 3 stacks." },
  { name: "Dash Power Lv2", tier: 2, desc: "When using Evasion, for 3 seconds, ATK increases by 20 and ASPD increases by 150. Max 3 stacks." },
  { name: "Engineer Lv2", tier: 2, desc: "Dealing damage to a target increases ATK and MATK by 15, and also CSPD by 10 for 20 seconds. Higher TEC leads to a greater increase. Activates once every 10 seconds." },
  { name: "Fighting Magica Lv2", tier: 2, desc: "Dealing damage to a target increases MATK by 2 for 4 seconds. Max 150 stacks." },
  { name: "Fighting Power Lv2", tier: 2, desc: "Dealing damage to a target increases ATK by 2 for 2 seconds. Max 150 stacks." },
  { name: "Foreseen Evasion Lv2", tier: 2, desc: "When the target performs an Evasion (excluding events), Anticipate increases by 10% for 12 seconds." },
  { name: "Gearshift Lv2", tier: 2, desc: "Dealing damage to a target increases ASPD by 40 for 3 seconds. Max 20 stacks." },
  { name: "Graze Mana Lv2", tier: 2, desc: "Restores 10 MP if your attack is a Graze. Activation Power 20." },
  { name: "Graze Mana Boost Lv2", tier: 2, desc: "If your attack is a Graze, for 15 seconds, MaxMP decreases by 250, but Short and Long Range Damage increase by 1%, and Accuracy increases by 120. Max 3 stacks." },
  { name: "Graze Precision Lv2", tier: 2, desc: "If your attack is a Graze, Accuracy increases by 40 for 30 seconds. Max 5 stacks." },
  { name: "Guarded Advantage Lv2", tier: 2, desc: "When the target performs a Guard (excluding events), Guard Break increases by 10% for 12 seconds." },
  { name: "Guarded Magica Lv2", tier: 2, desc: "When the target performs a Guard (excluding events), MATK increases by 50 for 15 seconds. Higher DEX leads to greater increase. Activates once every 20 seconds." },
  { name: "Guarded Recovery Lv2", tier: 2, desc: "Restores 1500 HP when the target performs a Guard (excluding events). HP restored increases based on STR. Activates once every 6 seconds." },
  { name: "Health Barrier Lv2", tier: 2, desc: "Dealing damage to a target increases Physical Barrier and Magic Barrier by 4 for 6 seconds. Higher MTL leads to a greater increase. Max 100 stacks." },
  { name: "Life Purge Lv2", tier: 2, desc: "When taking damage from a target, for 20 seconds, MaxHP decreases by 2%, but ASPD increases by 100. Max 5 stacks." },
  { name: "Lucky Experience Lv2", tier: 2, desc: "Dealing damage to a target increases EXP Gain by 2% for 77 seconds. Max number of stacks increases based on LUK. Max 10 stacks." },
  { name: "Magica Rebound Lv2", tier: 2, desc: "If your attack is a MISS, MATK increases by 20 for 30 seconds. Max 10 stacks." },
  { name: "Mana Combat Lv2", tier: 2, desc: "Restores 2 MP when taking damage from a target, MP restored increases based on VIT." },
  { name: "Mana Rebound Lv2", tier: 2, desc: "Restores 100 MP if your attack is a MISS. Activation Power 20." },
  { name: "Mega Power Rebound Lv2", tier: 2, desc: "If your attack is a MISS, for 90 seconds, ATK increases by 200, Critical Rate increases by 75, and Accuracy decreases by 9999." },
  { name: "Nimble Lv2", tier: 2, desc: "Dealing damage to a target increases Dodge by 2 for 6 seconds. Max 30 stacks." },
  { name: "Power Rebound Lv2", tier: 2, desc: "If your attack is a MISS, ATK increases by 20 for 30 seconds. Max 10 stacks." },
  { name: "Precision Lv2", tier: 2, desc: "Dealing damage to a target increases Accuracy by 2 for 6 seconds. Max 30 stacks." },
  { name: "Spirit Blow Lv2", tier: 2, desc: "Dealing damage to a target restores 4 MP. MP restored increases based on AGI. Activates once every 6 seconds." },
  { name: "Spirit Shot Lv2", tier: 2, desc: "Dealing damage to a target restores 4 MP. MP restored increases based on DEX. Activates once every 6 seconds." },
  { name: "Vengeful Life Lv2", tier: 2, desc: "When taking damage from a target, MaxHP increases by 100 for 180 seconds. Max 100 stacks." },
  { name: "Vengeful Magica Lv2", tier: 2, desc: "When taking damage from a target, MATK increases by 15 for 30 seconds. Max 60 stacks." },
  { name: "Vengeful Mana Lv2", tier: 2, desc: "When taking damage from a target, Max MP increases by 10 for 180 seconds. Max 25 stacks." },
  { name: "Vengeful Power Lv2", tier: 2, desc: "When taking damage from a target, ATK increases by 15 for 30 seconds. Max 60 stacks." },
  { name: "Vengeful Samurai Lv2", tier: 2, desc: "When taking damage from a target, Unsheathe Power increases by 100 for 9 seconds. Max 2 stacks." },

  // 🔵 TIER III
  { name: "Tumble Unavailable", tier: 3, desc: "Can no longer inflict [Tumble]." },
  { name: "STR +3", tier: 3, desc: "STR increases by 3." },
  { name: "INT +3", tier: 3, desc: "INT increases by 3." },
  { name: "VIT +3", tier: 3, desc: "VIT increases by 3." },
  { name: "AGI +3", tier: 3, desc: "AGI increases by 3." },
  { name: "DEX +3", tier: 3, desc: "DEX increases by 3." },
  { name: "MaxHP +600", tier: 3, desc: "MaxHP increases by 600." },
  { name: "MaxMP +30", tier: 3, desc: "MaxMP increases by 30." },
  { name: "ATK +15", tier: 3, desc: "ATK increases by 15." },
  { name: "MATK +15", tier: 3, desc: "MATK increases by 15." },
  { name: "DEF +30", tier: 3, desc: "DEF increases by 30." },
  { name: "MDEF +30", tier: 3, desc: "MDEF increases by 30." },
  { name: "Accuracy +9", tier: 3, desc: "Accuracy increases by 9." },
  { name: "Dodge +9", tier: 3, desc: "Dodge increases by 9." },
  { name: "ASPD +150", tier: 3, desc: "ASPD increases by 150." },
  { name: "CSPD +150", tier: 3, desc: "CSPD increases by 150." },
  { name: "Natural HP Regen +45", tier: 3, desc: "Natural HP Regen increases by 45." },
  { name: "Natural MP Regen +15", tier: 3, desc: "Natural MP Regen increases by 15." },
  { name: "Critical Rate +3", tier: 3, desc: "Critical Rate increases by 3." },
  { name: "Critical Damage +3", tier: 3, desc: "Critical Damage increases by 3." },
  { name: "Exp Gain +9%", tier: 3, desc: "EXP gained from monsters increases by 9%." },
  { name: "Pet EXP Gain +18%", tier: 3, desc: "EXP gained by pets increases by 18%." },
  { name: "Battlecast Lv3", tier: 3, desc: "Dealing damage to a target increases CSPD by 60 for 6 seconds. Max 20 stacks." },
  { name: "Blood Regen Lv3", tier: 3, desc: "Dealing damage to a target restores 600 HP. HP restored increases based on STR. Activates once every 3 seconds." },
  { name: "Blood Spell Lv3", tier: 3, desc: "Dealing damage to a target restores 600 HP. HP restored increases based on INT. Activates every 3 seconds." },
  { name: "Bunker Edge Lv3", tier: 3, desc: "Dealing damage to a target increases Physical Pierce by 1% for 5 seconds. Activation Power 60. Max 10 stacks." },
  { name: "Bunker Magica Lv3", tier: 3, desc: "Dealing damage to a target increases Magic Pierce by 1% for 5 seconds. Activation Power 60. Max 10 stacks." },
  { name: "Counter Evasion Mana Lv3", tier: 3, desc: "Restores 60 MP when the target performs an Evasion (excluding events). MP restored increases based on INT. Activates once every 6 seconds." },
  { name: "Counter Evasion Power Lv3", tier: 3, desc: "When the target performs an Evasion (Excluding Events), Attack increases by 100 for 20 seconds. Higher DEX leads to a greater increase. Activates once every 20 seconds." },
  { name: "Counter Rage Lv3", tier: 3, desc: "When taking damage from a target, Aggro increases by 30% for 12 seconds." },
  { name: "Counter Speed Lv3", tier: 3, desc: "When taking damage from a target, ASPD, CSPD, and Action Speed increase by 6% for 3 seconds." },
  { name: "Critical Lv3", tier: 3, desc: "Dealing damage to a target increases Critical Rate by 1 for 3 seconds. Effect duration increases based on CRT. Max 30 stacks." },
  { name: "Critical Rebound Lv3", tier: 3, desc: "If your attack is MISS, Critical Rate increases by 12 for 60 seconds. Max 5 stacks." },
  { name: "Cursed Weapon Lv3", tier: 3, desc: "Dealing damage to a target reduces Max HP by 1% for 3 seconds, but increases ATK and MATK by 3. Max 99 stacks." },
  { name: "Dash Defence Lv3", tier: 3, desc: "When using Evasion, for 3 seconds, Physical and Magical Resistance increase by 6%. Max 3 stacks." },
  { name: "Dash Power Lv3", tier: 3, desc: "When using Evasion, for 3 seconds, ATK increases by 30 and ASPD increases by 200. Max 3 stacks." },
  { name: "Engineer Lv3", tier: 3, desc: "Dealing damage to a target increases ATK and MATK by 20, and also CSPD by 10 for 20 seconds. Higher TEC leads to a greater increase. Activates once every 10 seconds." },
  { name: "Fighting Magica Lv3", tier: 3, desc: "Dealing damage to a target increases MATK by 3 for 4 seconds. Max 100 stacks." },
  { name: "Fighting Power Lv3", tier: 3, desc: "Dealing damage to a target increases ATK by 3 for 2 seconds. Max 100 stacks." },
  { name: "Foreseen Evasion Lv3", tier: 3, desc: "When the target performs an Evasion (excluding events), Anticipate increases by 15% for 12 seconds." },
  { name: "Gearshift Lv3", tier: 3, desc: "Dealing damage to a target increases ASPD by 60 for 3 seconds. Max 20 stacks." },
  { name: "Graze Mana Lv3", tier: 3, desc: "Restores 10 MP if your attack is a Graze. Activation Power 30." },
  { name: "Graze Mana Boost Lv3", tier: 3, desc: "If your attack is a Graze, for 15 seconds, MaxMP decreases by 200, but Short and Long Range Damage increases by 1%, and Accuracy increases by 180. Max 3 stacks." },
  { name: "Graze Precision Lv3", tier: 3, desc: "If your attack is a Graze, Accuracy increases by 60 for 30 seconds. Max 5 stacks." },
  { name: "Guarded Advantage Lv3", tier: 3, desc: "When the target performs a Guard (excluding events), Guard Break increases by 15% for 12 seconds." },
  { name: "Guarded Magica Lv3", tier: 3, desc: "When the target performs a Guard (excluding events), MATK increases by 50 for 20 seconds. Higher DEX leads to a greater increase. Activates once every 20 seconds." },
  { name: "Guarded Recovery Lv3", tier: 3, desc: "Restores 2000 HP when the target performs a Guard (excluding events). HP restored increases based on STR. Activates once every 6 seconds." },
  { name: "Health Barrier Lv3", tier: 3, desc: "Dealing damage to a target increases Physical Barrier and Magic Barrier by 6 for 6 seconds. Higher MTL leads to a greater increase. Max 100 stacks." },
  { name: "Life Purge Lv3", tier: 3, desc: "When taking damage from a target, for 20 seconds, MaxHP decreases by 4%, but ASPD increases by 200. Max 5 stacks." },
  { name: "Lucky Experience Lv3", tier: 3, desc: "Dealing damage to a target increases EXP Gain by 3% for 77 seconds. Max number of stacks increases based on LUK. Max 10 stacks." },
  { name: "Magica Rebound Lv3", tier: 3, desc: "If your attack is a MISS, MATK increases by 30 for 30 seconds. Max 10 stacks." },
  { name: "Mana Combat Lv3", tier: 3, desc: "Restores 3 MP when taking damage from a target, MP restored increases based on VIT." },
  { name: "Mana Rebound Lv3", tier: 3, desc: "Restores 100 MP if your attack is a MISS. Activation Power 30." },
  { name: "Mega Power Rebound Lv3", tier: 3, desc: "If your attack is a MISS, for 90 seconds, ATK increases by 300, Critical Rate increases by 100, and Accuracy decreases by 9999." },
  { name: "Nimble Lv3", tier: 3, desc: "Dealing damage to a target increases Dodge by 3 for 6 seconds. Max 30 stacks." },
  { name: "Power Rebound Lv3", tier: 3, desc: "If your attack is a MISS, ATK increases by 30 for 30 seconds. Max 10 stacks." },
  { name: "Precision Lv3", tier: 3, desc: "Dealing damage to a target increases Accuracy by 3 for 6 seconds. Max 30 stacks." },
  { name: "Spirit Blow Lv3", tier: 3, desc: "Dealing damage to a target restores 6 MP. MP restored increases based on AGI. Activates once every 6 seconds." },
  { name: "Spirit Shot Lv3", tier: 3, desc: "Dealing damage to a target restores 6 MP. MP restored increases based on DEX. Activates once every 6 seconds." },
  { name: "Vengeful Life Lv3", tier: 3, desc: "When taking damage from a target, MaxHP increases by 200 for 180 seconds. Max 80 stacks." },
  { name: "Vengeful Magica Lv3", tier: 3, desc: "When taking damage from a target, MATK increases by 30 for 30 seconds. Max 30 stacks." },
  { name: "Vengeful Mana Lv3", tier: 3, desc: "When taking damage from a target, Max MP increases by 20 for 180 seconds. Max 20 stacks." },
  { name: "Vengeful Power Lv3", tier: 3, desc: "When taking damage from a target, ATK increases by 30 for 30 seconds. Max 30 stacks." },
  { name: "Vengeful Samurai Lv3", tier: 3, desc: "When taking damage from a target, Unsheathe Power increases by 100 for 9 seconds. Max 3 stacks." },

  // 🟣 TIER IV
  { name: "STR +4", tier: 4, desc: "STR increases by 4." },
  { name: "INT +4", tier: 4, desc: "INT increases by 4." },
  { name: "VIT +4", tier: 4, desc: "VIT increases by 4." },
  { name: "AGI +4", tier: 4, desc: "AGI increases by 4." },
  { name: "DEX +4", tier: 4, desc: "DEX increases by 4." },
  { name: "MaxHP +800", tier: 4, desc: "MaxHP increases by 800." },
  { name: "MaxMP +40", tier: 4, desc: "MaxMP increases by 40." },
  { name: "ATK +20", tier: 4, desc: "ATK increases by 20." },
  { name: "MATK +20", tier: 4, desc: "MATK increases by 20." },
  { name: "DEF +40", tier: 4, desc: "DEF increases by 40." },
  { name: "MDEF +40", tier: 4, desc: "MDEF increases by 40." },
  { name: "Accuracy +12", tier: 4, desc: "Accuracy increases by 12." },
  { name: "Dodge +12", tier: 4, desc: "Dodge increases by 12." },
  { name: "ASPD +200", tier: 4, desc: "ASPD increases by 200." },
  { name: "CSPD +200", tier: 4, desc: "CSPD increases by 200." },
  { name: "Natural HP Regen +60", tier: 4, desc: "Natural HP Regen increases by 60." },
  { name: "Natural MP Regen +20", tier: 4, desc: "Natural MP Regen increases by 20." },
  { name: "Critical Rate +4", tier: 4, desc: "Critical Rate increases by 4." },
  { name: "Critical Damage +4", tier: 4, desc: "Critical Damage increases by 4." },
  { name: "Exp Gain +12%", tier: 4, desc: "EXP gained from monsters increases by 12%." },
  { name: "Pet EXP Gain +24%", tier: 4, desc: "EXP gained by pets increases by 24%." },
  { name: "Battlecast Lv4", tier: 4, desc: "Dealing damage to a target increases CSPD by 80 for 6 seconds. Max 20 stacks." },
  { name: "Blood Regen Lv4", tier: 4, desc: "Dealing damage to a target restores 800 HP. HP restored increases based on STR. Activates once every 3 seconds." },
  { name: "Blood Spell Lv4", tier: 4, desc: "Dealing damage to a target restores 800 HP. HP restored increases based on INT. Activates every 3 seconds." },
  { name: "Bunker Edge Lv4", tier: 4, desc: "Dealing damage to a target increases Physical Pierce by 1% for 5 seconds. Activation Power 80. Max 10 stacks." },
  { name: "Bunker Magica Lv4", tier: 4, desc: "Dealing damage to a target increases Magic Pierce by 1% for 5 seconds. Activation Power 80. Max 10 stacks." },
  { name: "Counter Evasion Mana Lv4", tier: 4, desc: "Restores 80 MP when the target performs an Evasion (excluding events). MP restored increases based on INT. Activates once every 6 seconds." },
  { name: "Counter Evasion Power Lv4", tier: 4, desc: "When the target performs an Evasion (Excluding Events), Attack increases by 100 for 25 seconds. Higher DEX leads to a greater increase. Activates once every 20 seconds." },
  { name: "Counter Rage Lv4", tier: 4, desc: "When taking damage from a target, Aggro increases by 40% for 12 seconds." },
  { name: "Counter Speed Lv4", tier: 4, desc: "When taking damage from a target, ASPD, CSPD, and Action Speed increase by 8% for 3 seconds." },
  { name: "Critical Lv4", tier: 4, desc: "Dealing damage to a target increases Critical Rate by 1 for 3 seconds. Effect duration increases based on CRT. Max 40 stacks." },
  { name: "Critical Rebound Lv4", tier: 4, desc: "If your attack is MISS, Critical Rate increases by 16 for 60 seconds. Max 5 stacks." },
  { name: "Cursed Weapon Lv4", tier: 4, desc: "Dealing damage to a target reduces Max HP by 1% for 3 seconds, but increases ATK and MATK by 4. Max 99 stacks." },
  { name: "Dash Defence Lv4", tier: 4, desc: "When using Evasion, for 3 seconds, Physical and Magical Resistance increase by 8%. Max 3 stacks." },
  { name: "Dash Power Lv4", tier: 4, desc: "When using Evasion, for 3 seconds, ATK increases by 40 and ASPD increases by 250. Max 3 stacks." },
  { name: "Engineer Lv4", tier: 4, desc: "Dealing damage to a target increases ATK and MATK by 25, and also CSPD by 10 for 20 seconds. Higher TEC leads to a greater increase. Activates once every 10 seconds." },
  { name: "Fighting Magica Lv4", tier: 4, desc: "Dealing damage to a target increases MATK by 4 for 4 seconds. Max 75 stacks." },
  { name: "Fighting Power Lv4", tier: 4, desc: "Dealing damage to a target increases ATK by 4 for 2 seconds. Max 75 stacks." },
  { name: "Foreseen Evasion Lv4", tier: 4, desc: "When the target performs an Evasion (excluding events), Anticipate increases by 20% for 12 seconds." },
  { name: "Gearshift Lv4", tier: 4, desc: "Dealing damage to a target increases ASPD by 80 for 3 seconds. Max 20 stacks." },
  { name: "Graze Mana Lv4", tier: 4, desc: "Restores 10 MP if your attack is a Graze. Activation Power 50." },
  { name: "Graze Mana Boost Lv4", tier: 4, desc: "If your attack is a Graze, for 15 seconds, MaxMP decreases by 150, but Short and Long Range Damage increases by 1%, and Accuracy increases by 240. Max 3 stacks." },
  { name: "Graze Precision Lv4", tier: 4, desc: "If your attack is a Graze, Accuracy increases by 80 for 30 seconds. Max 5 stacks." },
  { name: "Guarded Advantage Lv4", tier: 4, desc: "When the target performs a Guard (excluding events), Guard Break increases by 20% for 12 seconds." },
  { name: "Guarded Magica Lv4", tier: 4, desc: "When the target performs a Guard (excluding events), MATK increases by 50 for 25 seconds. Higher DEX leads to greater increase. Activates once every 20 seconds." },
  { name: "Guarded Recovery Lv4", tier: 4, desc: "Restores 2500 HP when the target performs a Guard (excluding events). HP restored increases based on STR. Activates once every 6 seconds." },
  { name: "Health Barrier Lv4", tier: 4, desc: "Dealing damage to a target increases Physical Barrier and Magic Barrier by 8 for 6 seconds. Higher MTL leads to a greater increase. Max 100 stacks." },
  { name: "Life Purge Lv4", tier: 4, desc: "When taking damage from a target, for 20 seconds, MaxHP decreases by 8%, but ASPD increases by 400. Max 5 stacks." },
  { name: "Lucky Experience Lv4", tier: 4, desc: "Dealing damage to a target increases EXP Gain by 4% for 77 seconds. Max number of stacks increases based on LUK. Max 10 stacks." },
  { name: "Magica Rebound Lv4", tier: 4, desc: "If your attack is a MISS, MATK increases by 40 for 30 seconds. Max 10 stacks." },
  { name: "Mana Combat Lv4", tier: 4, desc: "Restores 4 MP when taking damage from a target, MP restored increases based on VIT." },
  { name: "Mana Rebound Lv4", tier: 4, desc: "Restores 100 MP if your attack is a MISS. Activation Power 50." },
  { name: "Mega Power Rebound Lv4", tier: 4, desc: "If your attack is a MISS, for 90 seconds, ATK increases by 400, Critical Rate increases by 125, and Accuracy decreases by 9999." },
  { name: "Nimble Lv4", tier: 4, desc: "Dealing damage to a target increases Dodge by 4 for 6 seconds. Max 30 stacks." },
  { name: "Power Rebound Lv4", tier: 4, desc: "If your attack is a MISS, ATK increases by 40 for 30 seconds. Max 10 stacks." },
  { name: "Precision Lv4", tier: 4, desc: "Dealing damage to a target increases Accuracy by 4 for 6 seconds. Max 30 stacks." },
  { name: "Spirit Blow Lv4", tier: 4, desc: "Dealing damage to a target restores 8 MP. MP restored increases based on AGI. Activates once every 6 seconds." },
  { name: "Spirit Shot Lv4", tier: 4, desc: "Dealing damage to a target restores 8 MP. MP restored increases based on DEX. Activates once every 6 seconds." },
  { name: "Vengeful Life Lv4", tier: 4, desc: "When taking damage from a target, MaxHP increases by 400 for 180 seconds. Max 60 stacks." },
  { name: "Vengeful Magica Lv4", tier: 4, desc: "When taking damage from a target, MATK increases by 60 for 30 seconds. Max 15 stacks." },
  { name: "Vengeful Mana Lv4", tier: 4, desc: "When taking damage from a target, Max MP increases by 40 for 180 seconds. Max 15 stacks." },
  { name: "Vengeful Power Lv4", tier: 4, desc: "When taking damage from a target, ATK increases by 60 for 30 seconds. Max 15 stacks." },
  { name: "Vengeful Samurai Lv4", tier: 4, desc: "When taking damage from a target, Unsheathe Power increases by 100 for 9 seconds. Max 4 stacks." },

  // 🟡 TIER V
  { name: "STR +5", tier: 5, desc: "STR increases by 5." },
  { name: "INT +5", tier: 5, desc: "INT increases by 5." },
  { name: "VIT +5", tier: 5, desc: "VIT increases by 5." },
  { name: "AGI +5", tier: 5, desc: "AGI increases by 5." },
  { name: "DEX +5", tier: 5, desc: "DEX increases by 5." },
  { name: "MaxHP +1000", tier: 5, desc: "MaxHP increases by 1000." },
  { name: "MaxMP +50", tier: 5, desc: "MaxMP increases by 50." },
  { name: "ATK +25", tier: 5, desc: "ATK increases by 25." },
  { name: "MATK +25", tier: 5, desc: "MATK increases by 25." },
  { name: "DEF +50", tier: 5, desc: "DEF increases by 50." },
  { name: "MDEF +50", tier: 5, desc: "MDEF increases by 50." },
  { name: "Accuracy +15", tier: 5, desc: "Accuracy increases by 15." },
  { name: "Dodge +15", tier: 5, desc: "Dodge increases by 15." },
  { name: "ASPD +250", tier: 5, desc: "ASPD increases by 250." },
  { name: "CSPD +250", tier: 5, desc: "CSPD increases by 250." },
  { name: "Natural HP Regen +75", tier: 5, desc: "Natural HP Regen increases by 75." },
  { name: "Natural MP Regen +25", tier: 5, desc: "Natural MP Regen increases by 25." },
  { name: "Critical Rate +5", tier: 5, desc: "Critical Rate increases by 5." },
  { name: "Critical Damage +5", tier: 5, desc: "Critical Damage increases by 5." },
  { name: "Exp Gain +15%", tier: 5, desc: "EXP gained from monsters increases by 15%." },
  { name: "Pet EXP Gain +30%", tier: 5, desc: "EXP gained by pets increases by 30%." },
  { name: "Battlecast Lv5", tier: 5, desc: "Dealing damage to a target increases CSPD by 100 for 6 seconds. Max 20 stacks." },
  { name: "Blood Regen Lv5", tier: 5, desc: "Dealing damage to a target restores 1000 HP. HP restored increases based on STR. Activates once every 3 seconds." },
  { name: "Blood Spell Lv5", tier: 5, desc: "Dealing damage to a target restores 1000 HP. HP restored increases based on INT. Activates every 3 seconds." },
  { name: "Bunker Edge Lv5", tier: 5, desc: "Dealing damage to a target increases Physical Pierce by 1% for 5 seconds. Activation Power 100. Max 10 stacks." },
  { name: "Bunker Magica Lv5", tier: 5, desc: "Dealing damage to a target increases Magic Pierce by 1% for 5 seconds. Activation Power 100. Max 10 stacks." },
  { name: "Counter Evasion Mana Lv5", tier: 5, desc: "Restores 100 MP when the target performs an Evasion (excluding events). MP restored increases based on INT. Activates once every 6 seconds." },
  { name: "Counter Evasion Power Lv5", tier: 5, desc: "When the target performs an Evasion (Excluding Events), Attack increases by 100 for 30 seconds. Higher DEX leads to a greater increase. Activates once every 20 seconds." },
  { name: "Counter Rage Lv5", tier: 5, desc: "When taking damage from a target, Aggro increases by 50% for 12 seconds." },
  { name: "Counter Speed Lv5", tier: 5, desc: "When taking damage from a target, ASPD, CSPD, and Action Speed increase by 10% for 3 seconds." },
  { name: "Critical Lv5", tier: 5, desc: "Dealing damage to a target increases Critical Rate by 1 for 3 seconds. Effect duration increases based on CRT. Max 50 stacks." },
  { name: "Critical Rebound Lv5", tier: 5, desc: "If your attack is MISS, Critical Rate increases by 20 for 60 seconds. Max 5 stacks." },
  { name: "Cursed Weapon Lv5", tier: 5, desc: "Dealing damage to a target reduces Max HP by 1% for 3 seconds, but increases ATK and MATK by 5. Max 99 stacks." },
  { name: "Dash Defence Lv5", tier: 5, desc: "When using Evasion, for 3 seconds, Physical and Magical Resistance increase by 10%. Max 3 stacks." },
  { name: "Dash Power Lv5", tier: 5, desc: "When using Evasion, for 3 seconds, ATK increases by 50 and ASPD increases by 300. Max 3 stacks." },
  { name: "Engineer Lv5", tier: 5, desc: "Dealing damage to a target increases ATK and MATK by 30, and also CSPD by 10 for 20 seconds. Higher TEC leads to a greater increase. Activates once every 10 seconds." },
  { name: "Fighting Magica Lv5", tier: 5, desc: "Dealing damage to a target increases MATK by 5 for 4 seconds. Max 60 stacks." },
  { name: "Fighting Power Lv5", tier: 5, desc: "Dealing damage to a target increases ATK by 5 for 2 seconds. Max 60 stacks." },
  { name: "Foreseen Evasion Lv5", tier: 5, desc: "When the target performs an Evasion (excluding events), Anticipate increases by 25% for 12 seconds." },
  { name: "Gearshift Lv5", tier: 5, desc: "Dealing damage to a target increases ASPD by 100 for 3 seconds. Max 20 stacks." },
  { name: "Graze Mana Lv5", tier: 5, desc: "Restores 10 MP if your attack is a Graze. Activation Power 100." },
  { name: "Graze Mana Boost Lv5", tier: 5, desc: "If your attack is a Graze, for 15 seconds, MaxMP decreases by 100, but Short and Long Range Damage increases by 1%, and Accuracy increases by 300. Max 3 stacks." },
  { name: "Graze Precision Lv5", tier: 5, desc: "If your attack is a Graze, Accuracy increases by 100 for 30 seconds. Max 5 stacks." },
  { name: "Guarded Advantage Lv5", tier: 5, desc: "When the target performs a Guard (excluding events), Guard Break increases by 25% for 12 seconds." },
  { name: "Guarded Magica Lv5", tier: 5, desc: "When the target performs a Guard (excluding events), MATK increases by 50 for 20 seconds. Higher DEX leads to a greater increase. Activates once every 20 seconds." },
  { name: "Guarded Recovery Lv5", tier: 5, desc: "Restores 3000 HP when the target performs a Guard (excluding events). HP restored increases based on STR. Activates once every 6 seconds." },
  { name: "Health Barrier Lv5", tier: 5, desc: "Dealing damage to a target increases Physical Barrier and Magic Barrier by 10 for 6 seconds. Higher MTL leads to a greater increase. Max 100 stacks." },
  { name: "Life Purge Lv5", tier: 5, desc: "When taking damage from a target, for 20 seconds, MaxHP decreases by 16%, but ASPD increases by 800. Max 5 stacks." },
  { name: "Lucky Experience Lv5", tier: 5, desc: "Dealing damage to a target increases EXP Gain by 5% for 77 seconds. Max number of stacks increases based on LUK. Max 10 stacks." },
  { name: "Magica Rebound Lv5", tier: 5, desc: "If your attack is a MISS, MATK increases by 50 for 30 seconds. Max 10 stacks." },
  { name: "Mana Combat Lv5", tier: 5, desc: "Restores 5 MP when taking damage from a target, MP restored increases based on VIT." },
  { name: "Mana Rebound Lv5", tier: 5, desc: "Restores 100 MP if your attack is a MISS. Activation Power 100." },
  { name: "Mega Power Rebound Lv5", tier: 5, desc: "If your attack is a MISS, for 90 seconds, ATK increases by 500, Critical Rate increases by 150, and Accuracy decreases by 9999." },
  { name: "Nimble Lv5", tier: 5, desc: "Dealing damage to a target increases Dodge by 5 for 6 seconds. Max 30 stacks." },
  { name: "Power Rebound Lv5", tier: 5, desc: "If your attack is a MISS, ATK increases by 50 for 30 seconds. Max 10 stacks." },
  { name: "Precision Lv5", tier: 5, desc: "Dealing damage to a target increases Accuracy by 5 for 6 seconds. Max 30 stacks." },
  { name: "Spirit Blow Lv5", tier: 5, desc: "Dealing damage to a target restores 10 MP. MP restored increases based on AGI. Activates once every 6 seconds." },
  { name: "Spirit Shot Lv5", tier: 5, desc: "Dealing damage to a target restores 10 MP. MP restored increases based on DEX. Activates once every 6 seconds." },
  { name: "Vengeful Life Lv5", tier: 5, desc: "When taking damage from a target, MaxHP increases by 800 for 180 seconds. Max 40 stacks." },
  { name: "Vengeful Magica Lv5", tier: 5, desc: "When taking damage from a target, MATK increases by 90 for 30 seconds. Max 10 stacks." },
  { name: "Vengeful Mana Lv5", tier: 5, desc: "When taking damage from a target, Max MP increases by 80 for 180 seconds. Max 10 stacks." },
  { name: "Vengeful Power Lv5", tier: 5, desc: "When taking damage from a target, ATK increases by 90 for 30 seconds. Max 10 stacks." },
  { name: "Vengeful Samurai Lv5", tier: 5, desc: "When taking damage from a target, Unsheathe Power increases by 100 for 9 seconds. Max 5 stacks." },

  // Transfer Fail
  { name: "Radiant Chance", tier: 0, desc: "The success rate of Trait Transfer increases by 10% * Radiance Chance Level. Changes to 'Radiant Chance Lv+1' upon failure. Max Level: Level 9." },
];

const tierEmoji = { 0: "🔁", 1: "⚪", 2: "🟢", 3: "🔵", 4: "🟣", 5: "🟡" };
const tierName  = { 0: "Transfer Fail", 1: "Tier I", 2: "Tier II", 3: "Tier III", 4: "Tier IV", 5: "Tier V" };

/**
 * Search abilities by name keyword (case-insensitive, partial match)
 * @param {string} query
 * @returns {Array}
 */
function searchAbility(query) {
  const q = query.toLowerCase().trim();
  return abilities.filter(a => a.name.toLowerCase().includes(q));
}

/**
 * Get all abilities of a specific tier
 * @param {number} tier
 * @returns {Array}
 */
function getByTier(tier) {
  return abilities.filter(a => a.tier === tier);
}

/**
 * Format a single ability into a message string
 */
function formatAbility(a) {
  const emoji = tierEmoji[a.tier] || "❓";
  const tier  = tierName[a.tier]  || "Unknown";
  return `${emoji} *${a.name}*\n🏅 Tier: ${tier}\n📖 ${a.desc}`;
}

module.exports = { searchAbility, getByTier, formatAbility, tierEmoji, tierName, abilities };